version: '3.8'

services:
  # PostgreSQL for Travel App
  trip:
    image: postgres:latest
    container_name: trip
    environment:
      POSTGRES_DB: tripdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  # PostgreSQL for Email Service
  email:
    image: postgres:latest
    container_name: email
    environment:
      POSTGRES_DB: emaildb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"  # Exposing on a different port to avoid conflict

  # Redis for caching (Used by Travel App)
  redis:
    image: redis:latest
    container_name: redis-cache
    ports:
      - "6379:6379"

  # Apache Kafka dependencies
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  # Travel Application (Producer)
  travel:
    build: ./travel
    container_name: travel
    ports:
      - "8080:8080"
    depends_on:
      - trip
      - kafka
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://trip:5432/tripdb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379

  # Email Service (Consumer)
  emailservice:
    build: ./emailservice
    container_name: emailservice
    ports:
      - "8081:8081"
    depends_on:
      - email
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://email:5432/emaildb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
