# Use OpenJDK base image
FROM openjdk:17-jdk-slim

# Set working directory
WORKDIR /app

# Create app directory
RUN mkdir -p /app

# Copy JAR file (Replace 'travel-application.jar' with your actual JAR file name)
COPY target/travel-0.0.1-SNAPSHOT.jar app.jar

# Expose the necessary port
EXPOSE 8080

# Set environment variables (These values can be overridden by docker-compose)
ENV SPRING_DATASOURCE_URL=jdbc:postgresql://trip:5432/tripdb
ENV SPRING_DATASOURCE_USERNAME=admin
ENV SPRING_DATASOURCE_PASSWORD=admin
ENV SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
ENV SPRING_REDIS_HOST=redis
ENV SPRING_REDIS_PORT=6379

# Run the application
CMD ["java", "-jar", "app.jar"]
